### ISSUE TITLE
[Forge 1.19.2] Unable to Launch

### ISSUE THREAD

**Issue by ardissaps** [frikinjay/let-me-despawn#1]
Log : https://mclo.gs/dDSLUer
Crash Log : https://mclo.gs/hbGXPc5
Latest Log : https://mclo.gs/wNuOzbj

**Comment by ardissaps** [comment]
I also only installed your mod with no other mods at all, log LMD only  : https://mclo.gs/eKSJxJf

**Comment by frikinjay** [comment]
fixed in 1.0.1

**Comment by ardissaps** [comment]
@frikinjay 
![image](https://user-images.githubusercontent.com/82106625/186179870-835b8fb0-801e-4376-a535-73291e66511b.png)

Full Log : https://mclo.gs/wZOy3hu
Latest Log : https://aofpaste.com/uyusizadil.yaml
Crash Log : https://aofpaste.com/efokixecic.properties

**Comment by ardissaps** [comment]
thanks!
