### ISSUE TITLE
[1.20.1] Crash when loading game.

### ISSUE THREAD

**Issue by Gbergz** [frikinjay/let-me-despawn#11]
## Title^

**MC:** 1.20.1
**Forge:** 47.0.19
**Let Me Despawn:** 1.1.1 | https://www.curseforge.com/minecraft/mc-mods/let-me-despawn/files/4615889

**Logs:** https://gist.githubusercontent.com/Gbergz/820a61ebf5461d80aaac0fc81c827134/raw/4cb8c53aeb202a277b76bf1c1b5c3231bdff64f9/gistfile1.txt

**Notes:**
No additional mods added, only Forge(47.0.19) & Let Me Despawn installed.

**-** Gbergz

**Comment by 630R63** [comment]
In the time that it took me to document my issue, you opened one for the exact same problem :D 
I'm glad I'm not the only one with this issue :)

**Comment by frikinjay** [comment]
Fixed it
