### ISSUE TITLE
fabric 1.20.1 server crash

### ISSUE THREAD

**Issue by dadoirie** [frikinjay/let-me-despawn#15]
no idea whats causing it, but looks like it's trying to access something which doesn't exist anymore

[crash-report](https://mclo.gs/KFv5q3G)
[latest log](https://mclo.gs/EBnlq5t) (error at line: [2468](https://mclo.gs/EBnlq5t#L2468))

**Comment by frikinjay** [comment]
Fixed in 1.2.0
