### ISSUE TITLE
Item stacking issue / Fabric Server 1.20.4

### ISSUE THREAD

**Issue by AugustusZebulon** [frikinjay/let-me-despawn#23]
Hi!

I found an issue with a simple zombie farm where rotten flesh would not stack in the chest until I tossed it out on the ground, not even in my inventory. Once I removed the mod it stacks like normal in the chest and inventory. 

Server is Fabric 1.20.4 with : 

- Clumps Fabric 15.0.0.2
- Fabric API 0.92.0
- Ferritecore 6.0.3
- Krypton 0.2.6
- Lithium 0.12.1
- ModernFix 5.13.0
- Noisium 1.0.2
- Servercore 1.4.0
- Starlight 1.1.3
- ThreadTweak 0.1.2

**Comment by frikinjay** [comment]
This is a very niche issue and occurs very randomly, hopefully fixed in newer versions but I am still trying to track down the issue in older versions

**Comment by frikinjay** [comment]
Fixed in 1.2.1 release
