### ISSUE TITLE
the new mod version for 1.20.1 is not working

### ISSUE THREAD

**Issue by peow** [frikinjay/let-me-despawn#24]
the newest mod version (**1.2.0**) isnt working

I did some tests and came to this conclusion
In these prints I'm using the mod in the old version (1.1.0) and everything seems to be working fine
![2024-02-06_14 35 07](https://github.com/frikinjay/let-me-despawn/assets/105888751/17361760-a56e-4f4b-9c41-c04b3ca98354)
I threw armor into a hole and put a Husk in there, and then he equipped the armor
![2024-02-06_14 35 20](https://github.com/frikinjay/let-me-despawn/assets/105888751/d33d33ab-1faf-4436-9acb-d65b13b701a7)

I went to a very deep cave, and came back, when I came back the armor was dropped on the floor
![2024-02-06_14 35 58](https://github.com/frikinjay/let-me-despawn/assets/105888751/64aae1f9-a0de-42e1-a296-429286efdfa6)

------------------

* now with the latest version of the mod (**1.2.0**), I did the same thing
![2024-02-06_14 36 54](https://github.com/frikinjay/let-me-despawn/assets/105888751/6477cfed-1c16-42ae-8af3-9c4796b004a1)
![2024-02-06_14 37 02](https://github.com/frikinjay/let-me-despawn/assets/105888751/c59b0f9b-91c5-4d48-9db4-369686a70450)

and then after going back under the cave, the Husk was gone and the armor didn't drop
![2024-02-06_14 37 33](https://github.com/frikinjay/let-me-despawn/assets/105888751/08aaab2d-b79d-46dd-82eb-f75036729986)

I reran this test several times to be sure

-------------------

Since in new worlds, mobs do not equip armor that is on the ground (due to Local Difficulty) in these tests I am using a mod called Grabby Mobs, which makes mobs pick up any item from the ground, at any time

my log: 
[latest.log](https://github.com/frikinjay/let-me-despawn/files/14184284/latest.log)

* when fixing this bug, I ask you to post an update for fabric 1.20.1 with support to fabric loader 0.14.22

**Comment by frikinjay** [comment]
Should be fixed in the 1.2.1 release.
