### ISSUE TITLE
dont work in 1.20.1 fabric server

### ISSUE THREAD

**Issue by Domen-1** [frikinjay/let-me-despawn#25]
I have my own fabric server and installed this mod there to get rid of such cases (screenshot) or from endermen in the nether with blocks in their hands, but this mod did not help at all, these mobs stood with objects and still stand
![image](https://github.com/frikinjay/let-me-despawn/assets/111240419/0e26702f-da66-444b-9937-752e0b3f4f3e)

**Comment by frikinjay** [comment]
I would need a list of additional mods you have installed

**Comment by Domen-1** [comment]
![image](https://github.com/user-attachments/assets/7d0306f4-28b9-42ca-98a0-63f79bcbb10d)
![image](https://github.com/user-attachments/assets/a8be30a0-e00e-47aa-9dff-f1772cab5bb4)

**Comment by Domen-1** [comment]
and i think this mob's won't disapwn because i installed this mod after the mod appeared

**Comment by frikinjay** [comment]
Yes, the mod will only help with mobs that spawn after youve added the mod
