### ISSUE TITLE
Flagged as compatible with 1.20.6 on Curseforge 

### ISSUE THREAD

**Issue by SMUGLORD** [frikinjay/let-me-despawn#29]
On Curseforge, your mod is flagged as compatible with 1.20.6 which is actually not and causes crashes.

![image](https://github.com/frikinjay/let-me-despawn/assets/39859596/3962db58-9006-4314-b237-f9791532b50a)

crashreport : https://pastebin.com/rY7rhCfj

**Comment by frikinjay** [comment]
1.2.1 is now compatible with 1.20.5 and up with some extra features
