### ISSUE TITLE
Server Crash with Error: Ticking entity  java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Tiegertosch** [frikinjay/let-me-despawn#31]
[crash-2024-05-25_19.13.18-server.txt](https://github.com/frikinjay/let-me-despawn/files/15444335/crash-2024-05-25_19.13.18-server.txt)

**Comment by Un1q32** [comment]
Happens whenever a mob picks up loot from the ground

**Comment by frikinjay** [comment]
1.2.1 is now compatible with 1.20.5 and up with some extra features.
