### ISSUE TITLE
Fabric 1.20.6 doesn't work server-side

### ISSUE THREAD

**Issue by sternschnaube** [frikinjay/let-me-despawn#32]
![image](https://github.com/frikinjay/let-me-despawn/assets/120551916/cf7aeefc-9178-481f-a5dd-f6492bd91092)

https://pastebin.com/raw/N5fXNtSx

**Comment by frikinjay** [comment]
The next version will be server side, I am still figuring it out due to the new changes in the nbt system

**Comment by sternschnaube** [comment]
Thanks!
