### ISSUE TITLE
Mobs do not appear

### ISSUE THREAD

**Issue by Solmeyt** [frikinjay/let-me-despawn#36]
All mobs specified in the configuration do not appear or appear very little
Version : Minecraft 1.21 with Fabric 0.15.11

**Comment by jiangXYqaq** [comment]
Ver Minecraft 1.20.1 fabric server letmedespawn-fabric-1.20.x-1.2.1
same issue. I use spawn egg to summon mob in config, they don't disappear at all.

**Comment by frikinjay** [comment]
Are you using any additional mods? I'll need a list. This should'nt affect mob spawns in said way

**Comment by frikinjay** [comment]
Fixed in 1.3.1

**Comment by Solmeyt** [comment]
Thanks !
