### ISSUE TITLE
Mobs from config don't despawn after hitting despawn range

### ISSUE THREAD

**Issue by FNewel** [frikinjay/let-me-despawn#37]
When the Let Me Despawn mod is on the server, mobs from the config file are not despawned after the player leaves despawn sphere. The remaining mobs will despawn.

I'm also attaching a log ([2024-07-27-7.log](https://github.com/user-attachments/files/16400685/2024-07-27-7.log)) from turning on the server and my "test" teleport to high altitude due to despawn.

- Let Me Despawn version is 1.3.0 - Fabric
- Minecraft 1.21 with Fabric Loader 0.15.11

Let Me Despawn config (letmedespawn.json):
```
{
  "mobNames": [
    "minecraft:zombie"
  ]
}
```

These are all the mods that are on the server:
```
carpet-tis-addition-v1.61.1-mc1.21.jar
keep-xp-1.0.1.jar
BlueMap-5.3-fabric.jar
styled-chat-2.6.0+1.21.jar
placeholder-api-2.4.1+1.21.jar
serversleep-datapack.jar
*vmp-fabric-mc1.21-0.2.0+beta.7.163-all.jar
advancedchat-1.6-1.21.jar
letmedespawn-1.3.0.jar
melius-commands-1.1.0+1.21.jar
MaintenanceMode-Fabric-1.21-1.2.0.jar
LuckPerms-Fabric-5.4.133.jar
armor-stand-editor-2.5.0+1.21-rc1.jar
banhammer-0.11.0+1.21.jar
spark-1.10.73-fabric.jar
ledger-1.3.4.jar
orderedplayerlist-0.1.4+1.21.jar
styledplayerlist-3.5.1+1.21.jar
worldedit-mod-7.3.5.jar
votifier-1.1.jar
fabric-api-0.100.7+1.21.jar
*c2me-fabric-mc1.21-0.2.0+alpha.11.107.jar
vanilla-permissions-0.2.3+1.21.jar
fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar
vanish-1.5.6+1.21.jar
carpet-extra-1.21-1.4.147.jar
lithium-fabric-mc1.21-0.12.7.jar
*servux-fabric-1.21.0-0.2.0.jar
convenient-mobgriefing-2.1.2.jar
SimpleDiscordLink-Universal-3.1.3.jar
cloth-config-15.0.128-fabric.jar
CraterLib-Fabric-1.21-2.0.1.jar
InvView-1.4.15-1.20.5+.jar
*ferritecore-7.0.0-fabric.jar
essential_commands-0.35.2-mc1.21.jar
```
(*) Mods with an asterisk shouldn't be a problem, I tested it without them and the mobs still didn't despawn. Only after removing `letmedespawn-1.3.0.jar` they started to despawn.

**Comment by frikinjay** [comment]
Fixed in 1.3.1

**Comment by FNewel** [comment]
In the new version, mobs without an item in hand despawns but if they are holding an item, they don't seem to despawn. 

In config I only have zombies, I throw an iron axe at it and when flying off a despawn sphere or just waiting, the mob is still in place even though the rest around it despawns. I use the mods I listed above.

**Comment by frikinjay** [comment]
Yes, that is how the config works, if you have a mob in the config it will not despawn while its got items equipped.

**Comment by FNewel** [comment]
Aah, somehow I automatically thought it would work the other way around, that you need to set your mobs in config. It looks like it's working now, thank you.
