### ISSUE TITLE
Forge 1.20.1 || Permissions, Server - Client and no check if mob exist. 

### ISSUE THREAD

**Issue by zukkl** [frikinjay/let-me-despawn#38]
MC Version: 1.20.1 
Forge Version: 47.2.16
Mod Version: 1.20.1-1.20.4-1.2.1

1. changes can be made in the server config as a normal player. 
2. the commands cannot be deactivated using the permission mod/plugin. 
3. any string can be entered into the JSON without checking whether the mob exists (trivial)

https://www.youtube.com/watch?v=00kp_In11ok

**Comment by frikinjay** [comment]
Should be fixed in 1.3.2, I've left the option for any string to be inputted in the json incase for whatever reason the mob ID doesnt get populated in the options.
