### ISSUE TITLE
Crash on 1.3.2 (Forge 1.20.1)

### ISSUE THREAD

**Issue by emihead** [frikinjay/let-me-despawn#39]
This may be some kind of mod incompat but downgrading to 1.2.1 fixes it so it's definitely LMD related.

https://mclo.gs/UecaAk3

**Comment by Konhaiii** [comment]
Had same issue

**Comment by wolfieboy09** [comment]
I can confirm. This version mixin causes issues

**Comment by Barerock** [comment]
Same, curseforge.

**Comment by Mortycio** [comment]
Same. Downloaded with Prism Launcher from Modrinth.

**Comment by frikinjay** [comment]
I've found the issue, pushing 1.3.2b to both the platforms soon

**Comment by frikinjay** [comment]
Should be fixed in 1.3.2b

**Comment by Mortycio** [comment]
> Should be fixed in 1.3.2b

![image](https://github.com/user-attachments/assets/68cc6196-29d6-4d31-9eb8-351e762e0f0a)

**Comment by frikinjay** [comment]
You'll need fabric loader 0.16.5

**Comment by Mortycio** [comment]
> You'll need fabric loader 0.16.5

But that version will break a lot of other mods 😿

**Comment by frikinjay** [comment]
> > You'll need fabric loader 0.16.5
> 
> But that version will break a lot of other mods 😿

1.3.2c should work for other loader versions now
