### ISSUE TITLE
Qilt compatibility 

### ISSUE THREAD

**Issue by xboct02** [frikinjay/let-me-despawn#40]
Quilt Loader Version: 0.26.4

-- Error 1 --

Let Me Despawn requires version [0.16.5, ∞) of fabricloader, which is missing!

- <mods>/letmedespawn-fabric-1.3.2b.jar

-- Plugin State --

Cycle number = 1
Cycle Step = SOLVE

Loaded Plugins (2):
 - 'quilt_loader' (Builtin)
 - 'quilted_fabric_loader' (Builtin)

---- end of report ----

**Comment by frikinjay** [comment]
Should be fixed in 1.3.2c
