### ISSUE TITLE
1.20.1 Fabric 0.16.9 - mobs with held items delete held item when despawning

### ISSUE THREAD

**Issue by EnchantedBread** [frikinjay/let-me-despawn#45]
I don't have any proper proof of this but basically, I died and two zombies picked up some of my enchanted gear (Diamond sword & pickaxe) and when they despawned they took my tools with them (nothing else just those two tools got deleted)

I'm using a crap ton of mods so that could be the reason, but either way, that feature doesn't seem to be working for me.

modlist: https://drive.google.com/file/d/1wA8b5_2_9BQDyqPMQ0vtZxRQ28SelGwU/view?usp=sharing

modpack: https://drive.usercontent.google.com/download?id=1RfPkt6sjFZ7fsaQZCNoe89B9pnUsskPt&export=download

**Comment by frikinjay** [comment]
Have you tried with just lmd and almanac? To me seems like some other mod is responsible.
